// packages/video-editing-timeline-vue/example/example/src/App.vue
<template>
  <div id="app">
      <div class="title">
          视频编辑时间线例子
      </div>
       <div class="canvas-wrapper">
          <VideoEditingTimeline ref="timeline" :config="config" />
       </div>
  </div>
</template>

<script>
import VideoEditingTimeline from 'video-editing-timeline-vue';

export default {
  name: 'App',
  components: {
    VideoEditingTimeline
  },
  data() {
    return {
       config: {
            canvasWidth: 5000,
            canvasHeight: 50,
            minimumScale: 10, // 一个小刻度长度(单位px)
            minimumScaleTime: 1, // 一个小刻度代表时间（单位秒）
       }
    }
  },
  mounted() {
    const timeline = this.$refs.timeline;
    setTimeout(() => {
      this.config.minimumScale = 5;
    }, 2000);

  },
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.title {
      text-align: center;
      padding: 30px 0;
      font-size: 20px;
  }

  .canvas-wrapper {
      background-color: #111;
      overflow-x: auto;
  }
</style>

// packages/video-editing-timeline-react/example/src/App.js
import React, { useEffect, useState } from 'react';
import VideoEditingTimeline from "video-editing-timeline-react";
import './App.css';
function App() {
  const initConfig = {
    canvasWidth: 5000,
    canvasHeight: 50,
    minimumScale: 10, // 一个小刻度长度(单位px)
    minimumScaleTime: 1, // 一个小刻度代表时间（单位秒）
  }
  const [config, setConfig] = useState(initConfig)

  useEffect(()=>{
    setTimeout(() => {
      setConfig({ 
        canvasWidth: 5000,
        canvasHeight: 50,
        minimumScale: 10, // 一个小刻度长度(单位px)
        minimumScaleTime: 5, // 一个小刻度代表时间（单位秒）
      })
    }, 3000);
  },[])
  
  return (
    <div className="App">
     <div className="title">
          视频编辑时间线例子
      </div>
       <div className="canvas-wrapper">
          <VideoEditingTimeline  config={config} />
       </div>
    </div>
  );
}

export default App;
